#! /usr/bin/env python

import csv
import sys
import re
import argparse

parser = argparse.ArgumentParser(description='Convert a CSV of form responses into individual narrative documents.')
parser.add_argument('filename', help='the filename of the CSV to convert')
parser.add_argument('--title', nargs=1, help='the field, if any, to use for the document title')

def build_content(row, title_field):
    '''
    Builds the content
    '''
    response = ""
    for entry in row:
        if entry == title_field:
            response = '<h1>' + row[entry] + '</h1><br>' + response
        else:
            response += '<h2>' + entry + '</h2><br>'
            response += row[entry] + '<br>'
            response = re.sub('[\n\r]', '<br>', response)
    return response

def get_filename(row, index, title_field):
    '''
    Create a filename

    If there's a field called "Company's legal name", use that, but otherwise
    just create separate files from the iterable index
    '''
    try:
        return row[title_field] + '.html'
    except KeyError:
        return 'response{}.html'.format(str(index))

def convert(in_file, title_field):
    with open(in_file, newline='') as responses:
        r = csv.DictReader(responses)
        for index, row in enumerate(r):
            response = build_content(row, title_field)
            # Create file for this response
            filename = get_filename(row, index, title_field)
            with open(filename, 'w') as output:
                # Write to the file
                output.write(response)

if __name__ == "__main__":

    # Do a version check, since we need Python 3.6 or higher
    try:
        assert sys.version_info >= (3,6)
    except AssertionError:
        print('Error: Python 3.6 or higher is required.')
        print('Please install a compatible version of Python.')

    # Convert
    args = parser.parse_args()
    convert(args.filename, args.title)
